# Site settings
title: "David Gyulinyan CV"
description: "Resume"
url: "https://davidgyulinyan.com"

# Author information
author:
  name: "David Gyulinyan"
  email: "gyulinyand@gmail.com"

# Build settings
markdown: "none"
theme: "my-theme"
